apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-apps-init
  namespace: argocd #! - constans parameter
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.component_name }} #! - # that parameter is deliver form terraform appofapps
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
        - CreateNamespace=true
  destination:
    namespace: argocd
    server: {{ .Values.global.destination_server }} # that parameter is deliver form terraform appofapps
  source:
    repoURL: {{ .Values.global.appofapps_repourl }} # that parameter is deliver form terraform appofapps
    targetRevision: {{ .Values.global.target_revision }} # that parameter is deliver form terraform appofapps
    path: 02-apps-cm/01-init
    plugin:
      name: avp-hv-helm
    helm:
      parameters:
        - name: global.component_name
          value: {{ .Values.global.component_name }}
