---
apiVersion: v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
    replicas: 1
    selector:
        matchLabels:
        app: hello-world
    template:
        metadata:
        labels:
            app: hello-world
        spec:
        containers:
        - name: hello-world
            image: docker.io/bitnami/hello-world:latest
            ports:
            - containerPort: 8080
            env:
            - name: HELLO_WORLD
                valueFrom:
                configMapKeyRef:
                    name: myconfigmap
                    key: my-key